export * from './collections.interface';
export * from './credits.interface';
export * from './genres.interface';
export * from './movies.interface';
export * from './people.interface';
export * from './reviews.interface';
export * from './search.interface';
export * from './tv.interface';
export * from './tv-season.interface';